apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
  labels:
    name: demo-app
    app: vault-secrets-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: demo-app
  labels:
    app: vault-secrets-demo
