# VaultStaticSecret resources to sync secrets from Vault to Kubernetes
# These resources tell VSO which secrets to sync and where to store them

# Sync secrets from secret/myapp path in Vault
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: myapp-secret
  namespace: demo-app
  labels:
    app: vault-secrets-demo
spec:
  type: kv-v2
  mount: secret
  path: myapp
  destination:
    name: myapp-credentials
    create: true
  vaultAuthRef: vault-auth
  refreshAfter: 30s

---
# Sync secrets from secret/database path in Vault  
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: database-secret
  namespace: demo-app
  labels:
    app: vault-secrets-demo
spec:
  type: kv-v2
  mount: secret
  path: database
  destination:
    name: database-credentials
    create: true
  vaultAuthRef: vault-auth
  refreshAfter: 30s
